package section36_java16_features.feature_record_classes.after_records;

//  Records are immutable data classes that require only the type and name of fields.
// The equals, hashCode, and toString methods, as well as the private, final fields and public constructor, are generated by the Java compiler.
record Person(String name, String address)
{
    public static String UNKNOWN_ADDRESS = "Unknown";

    public static Person unnamed(String address) {
        return new Person("Unnamed", address);
    }
}
public class Example1
{
    public static void main(String[] args) {

        Person person = new Person("Pranay","Nagpur,Maharashtra");

        System.out.println(person); // record Generates toString() method
        System.out.println("Name : " + person.name()); // record Generates The Getter Method
        System.out.println("Address : " + person.address()); // record Generates The Getter Method
        System.out.println(person.hashCode()); // record Generates The Custom HashCode Method

        Person person1 = new Person("Diya","Napur,Maharashtra");
        System.out.println(person.equals(person1)); // record Generates The Custom Equals Method

        // Records Can Have Static Members And Static Methods
        System.out.println(Person.UNKNOWN_ADDRESS);
        Person person2 =  Person.unnamed("India");
        System.out.println(person2);
    }
}
